"""tenders

Revision ID: 562b49ff3fda
Revises: a2ae499a2109
Create Date: 2026-09-14 21:38:59.418264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562b49ff3fda'
down_revision: Union[str, Sequence[str], None] = 'a2ae499a2109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_profiles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('countries', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('regions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('sectors', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('domains', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('organization_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('market_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('technologies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('certifications', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('experience_level', sa.String(length=32), nullable=True),
    sa.Column('deadline_min_days', sa.Integer(), nullable=True),
    sa.Column('deadline_max_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_profiles_is_active'), 'search_profiles', ['is_active'], unique=False)
    op.create_table('tender_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_sources_is_enabled'), 'tender_sources', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_tender_sources_kind'), 'tender_sources', ['kind'], unique=False)
    op.create_table('tenders',
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('organization_type', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('market_type', sa.String(length=64), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('questions_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('search_profile_id', sa.Uuid(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_country'), 'tenders', ['country'], unique=False)
    op.create_index(op.f('ix_tenders_deadline_at'), 'tenders', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_tenders_fingerprint'), 'tenders', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_tenders_is_active'), 'tenders', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenders_reference'), 'tenders', ['reference'], unique=False)
    op.create_index(op.f('ix_tenders_search_profile_id'), 'tenders', ['search_profile_id'], unique=False)
    op.create_index(op.f('ix_tenders_sector'), 'tenders', ['sector'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_table('tender_documents',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('download_status', sa.String(length=16), nullable=False),
    sa.Column('extraction_status', sa.String(length=16), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_documents_sha256'), 'tender_documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_tender_documents_tender_id'), 'tender_documents', ['tender_id'], unique=False)
    op.create_table('tender_source_links',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title_seen', sa.String(length=512), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['tender_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_tender_source_links_source_id'), 'tender_source_links', ['source_id'], unique=False)
    op.create_index(op.f('ix_tender_source_links_tender_id'), 'tender_source_links', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_source_links_tender_id'), table_name='tender_source_links')
    op.drop_index(op.f('ix_tender_source_links_source_id'), table_name='tender_source_links')
    op.drop_table('tender_source_links')
    op.drop_index(op.f('ix_tender_documents_tender_id'), table_name='tender_documents')
    op.drop_index(op.f('ix_tender_documents_sha256'), table_name='tender_documents')
    op.drop_table('tender_documents')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_sector'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_search_profile_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_reference'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_is_active'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_fingerprint'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_deadline_at'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_country'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_tender_sources_kind'), table_name='tender_sources')
    op.drop_index(op.f('ix_tender_sources_is_enabled'), table_name='tender_sources')
    op.drop_table('tender_sources')
    op.drop_index(op.f('ix_search_profiles_is_active'), table_name='search_profiles')
    op.drop_table('search_profiles')
    # ### end Alembic commands ###
