"""tender analysis

Revision ID: b05c6d7e8f9a
Revises: af4b5c6d7e8f
Create Date: 2026-09-20 14:26:26.802028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05c6d7e8f9a'
down_revision: Union[str, Sequence[str], None] = 'af4b5c6d7e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_analyses',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('object', sa.Text(), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('budget', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('key_dates', sa.JSON(), nullable=False),
    sa.Column('deliverables', sa.JSON(), nullable=False),
    sa.Column('requested_documents', sa.JSON(), nullable=False),
    sa.Column('eligibility_conditions', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id')
    )
    op.create_table('tender_criteria',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_criteria_tender_id'), 'tender_criteria', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_criteria_tender_id'), table_name='tender_criteria')
    op.drop_table('tender_criteria')
    op.drop_table('tender_analyses')
    # ### end Alembic commands ###
