"""tender requirements

Revision ID: c16d7e8f9a0b
Revises: b05c6d7e8f9a
Create Date: 2026-09-20 17:07:22.414213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16d7e8f9a0b'
down_revision: Union[str, Sequence[str], None] = 'b05c6d7e8f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_requirements',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('evidence_required', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('manual_status', sa.Boolean(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['tender_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_requirements_category'), 'tender_requirements', ['category'], unique=False)
    op.create_index(op.f('ix_tender_requirements_status'), 'tender_requirements', ['status'], unique=False)
    op.create_index(op.f('ix_tender_requirements_tender_id'), 'tender_requirements', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_requirements_tender_id'), table_name='tender_requirements')
    op.drop_index(op.f('ix_tender_requirements_status'), table_name='tender_requirements')
    op.drop_index(op.f('ix_tender_requirements_category'), table_name='tender_requirements')
    op.drop_table('tender_requirements')
    # ### end Alembic commands ###
